name = "dumpert_plus_plus_sync"
type = 'webpack'
account_id = '69767181fecf889301ade720c821c984'
route = ''
zone_id = ''
usage_model = ''
workers_dev = true
target_type = "webpack"
kv_namespaces = [ 
  { binding = "SYNC", preview_id = "2616b484f9444f06a792205514bc1a60", id = "fbc41958afe941178992205a47b5aa30" }
]